[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ARIAC"
authors = [{name = "Pavel", email = "Pavel@NIST"}]
dynamic = ["version", "description"]
